version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/restaunax?schema=public"
      PORT: 5001
    
    # Prod
    # volumes:   
    #   - .:/usr/src/app
    # command: npm run dev 
      command: npm start


  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaunax
    ports:
      - "5432:5432"
    # Prod
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
